export const productsPageProducts = [
    {id: 1, title: 'Очки номер 1', url:"/images/newPhotos2/1.jpg",category:["all","Квадратные","Пластиковые"],name:"Nimani",subName:'Пластиковые,Квадратные'},
    {id: 2, title: 'Очки номер 2', url:"/images/newPhotos2/2.jpg",category:["all","Овальные","Пластиковые"],name:"Nimani",subName:'Пластиковые,Овальные'},
    {id: 3, title: 'Очки номер 2', url:"/images/newPhotos2/3.jpg",category:["all","Овальные","Пластиковые"],name:"Nimani",subName:'Пластиковые,Овальные'},
    {id: 4, title: 'Очки номер 2', url:"/images/newPhotos2/4.jpg",category:["all","Квадратные","Пластиковые"],name:"Nimani",subName:'Пластиковые,Квадратные'},
    {id: 5, title: 'Очки номер 2', url:"/images/newPhotos2/5.jpg",category:["all","Овальные","Пластиковые"],name:"Nimani",subName:'Пластиковые,Овальные'},
    {id: 6, title: 'Очки номер 2', url:"/images/newPhotos2/6.jpg",category:["all","Пластиковые","Прямоугольные"],name:"Nimani",subName:'Пластиковые,Прямоугольные'},
    {id: 7, title: 'Очки номер 2', url:"/images/newPhotos2/7.jpg",category:["all","Квадратные","Пластиковые"],name:"Nimani",subName:'Пластиковые,Квадратные'},
    {id: 8, title: 'Очки номер 2', url:"/images/newPhotos2/8.jpg",category:["all","Квадратные","Пластиковые"],name:"Nimani",subName:'Пластиковые,Квадратные'},
    {id: 9, title: 'Очки номер 2', url:"/images/newPhotos2/9.jpg",category:["all","Пластиковые","Прямоугольные"],name:"Nimani",subName:'Пластиковые,Прямоугольные'},
    {id: 10, title: 'Очки номер 2', url:"/images/newPhotos2/10.jpg",category:["all","Квадратные","Пластиковые"],name:"Nimani",subName:'Пластиковые,Квадратные'},
    {id: 11, title: 'Очки номер 2', url:"/images/newPhotos2/11.jpg",category:["all","Кошачий глаз","Пластиковые"],name:"POLIVIZOR",subName:'Пластиковые,"Кошачий глаз"'},
    {id: 12, title: 'Очки номер 2', url:"/images/newPhotos2/12.jpg",category:["all","Кошачий глаз","Пластиковые"],name:"NEOLOOK",subName:'Пластиковые,"Кошачий глаз"'},
    {id: 13, title: 'Очки номер 2', url:"/images/newPhotos2/13.jpg",category:["all","Кошачий глаз","Пластиковые"],name:"NEOLOOK",subName:'Пластиковые,"Кошачий глаз"'},
    {id: 14, title: 'Очки номер 2', url:"/images/newPhotos2/14.jpg",category:["all","Кошачий глаз","Пластиковые"],name:"RIVA",subName:'Пластиковые,"Кошачий глаз"'},
    {id: 15, title: 'Очки номер 2', url:"/images/newPhotos2/15.jpg",category:["all","Кошачий глаз","Пластиковые"],name:"RIVA",subName:'Пластиковые,"Кошачий глаз"'},
    {id: 16, title: 'Очки номер 2', url:"/images/newPhotos2/16.jpg",category:["all","Кошачий глаз","Пластиковые"],name:"RIVA",subName:'Пластиковые,"Кошачий глаз"'},
    {id: 17, title: 'Очки номер 2', url:"/images/newPhotos2/17.jpg",category:["all","Кошачий глаз","Пластиковые"],name:"RIVA",subName:'Пластиковые,"Кошачий глаз"'},
    {id: 18, title: 'Очки номер 2', url:"/images/newPhotos2/18.jpg",category:["all","Кошачий глаз","Металлические"],name:"Antonio Sordi",subName:'Металлические,"Кошачий глаз"'},
    {id: 19, title: 'Очки номер 2', url:"/images/newPhotos2/19.jpg",category:["all","Кошачий глаз","Пластиковые"],name:"POLIVIZOR",subName:'Пластиковые,"Кошачий глаз"'},
    {id: 20, title: 'Очки номер 2', url:"/images/newPhotos2/20.jpg",category:["all","Кошачий глаз","Пластиковые"],name:"Ligas",subName:'Пластиковые,"Кошачий глаз"'},
    {id: 21, title: 'Очки номер 2', url:"/images/newPhotos2/21.jpg",category:["all","Кошачий глаз","Пластиковые"],name:"POLIVIZOR",subName:'Пластиковые,"Кошачий глаз"'},
    {id: 22, title: 'Очки номер 2', url:"/images/newPhotos2/22.jpg",category:["all","Кошачий глаз","Металлические"],name:"Ligas",subName:'Металлические,"Кошачий глаз"'},
    {id: 23, title: 'Очки номер 2', url:"/images/newPhotos2/23.jpg",category:["all","Кошачий глаз","Металлические"],name:"NEOLOOK",subName:'Металлические,"Кошачий глаз"'},
    {id: 24, title: 'Очки номер 2', url:"/images/newPhotos2/24.jpg",category:["all","Пластиковые","Прямоугольные"],name:"Antonio Sordi",subName:'Пластиковые,Прямоугольные'},
    {id: 25, title: 'Очки номер 2', url:"/images/newPhotos2/25.jpg",category:["all","Кошачий глаз","Металлические"],name:"RIVA",subName:'Металлические,"Кошачий глаз"'},
    {id: 26, title: 'Очки номер 2', url:"/images/newPhotos2/26.jpg",category:["all","Кошачий глаз","Металлические"],name:"NEOLOOK",subName:'Металлические,"Кошачий глаз"'},
    {id: 27, title: 'Очки номер 2', url:"/images/newPhotos2/27.jpg",category:["all","Кошачий глаз","Металлические"],name:"Genex",subName:'Металлические,"Кошачий глаз"'},
    {id: 28, title: 'Очки номер 2', url:"/images/newPhotos2/28.jpg",category:["all","Кошачий глаз","Металлические"],name:"RIVA",subName:'Металлические,"Кошачий глаз"'},
    {id: 29, title: 'Очки номер 2', url:"/images/newPhotos2/29.jpg",category:["all","Кошачий глаз","Металлические"],name:"RIVA",subName:'Металлические,"Кошачий глаз"'},
    {id: 30, title: 'Очки номер 2', url:"/images/newPhotos2/30.jpg",category:["all","Металлические","Прямоугольные"],name:"Flavio",subName:'Металлические,Прямоугольные'},
    {id: 31, title: 'Очки номер 2', url:"/images/newPhotos2/31.jpg",category:["all","Металлические","Прямоугольные"],name:"Ricardo Rossi",subName:'Металлические,Прямоугольные'},
    {id: 32, title: 'Очки номер 2', url:"/images/newPhotos2/32.jpg",category:["all","Металлические","Прямоугольные"],name:"Ricardo Rossi",subName:'Металлические,Прямоугольные'},
    {id: 33, title: 'Очки номер 2', url:"/images/newPhotos2/33.jpg",category:["all","Металлические","Прямоугольные"],name:"Ballet",subName:'Металлические,Прямоугольные'},
    {id: 34, title: 'Очки номер 2', url:"/images/newPhotos2/34.jpg",category:["all","Металлические","Прямоугольные"],name:"Elfspirit",subName:'Металлические,Прямоугольные'},
    {id: 35, title: 'Очки номер 2', url:"/images/newPhotos2/35.jpg",category:["all","Металлические","Прямоугольные"],name:"Ballet",subName:'Металлические,Прямоугольные'},
    {id: 36, title: 'Очки номер 2', url:"/images/newPhotos2/36.jpg",category:["all","Металлические","Прямоугольные"],name:"Elfspirit",subName:'Металлические,Прямоугольные'},
    {id: 37, title: 'Очки номер 2', url:"/images/newPhotos2/37.jpg",category:["all","Пластиковые","Прямоугольные"],name:"Ballet",subName:'Пластиковые,Прямоугольные'},
    {id: 38, title: 'Очки номер 2', url:"/images/newPhotos2/38.jpg",category:["all","Пластиковые","Прямоугольные"],name:"ZENO",subName:'Пластиковые,Прямоугольные'},
    {id: 39, title: 'Очки номер 2', url:"/images/newPhotos2/39.jpg",category:["all","Пластиковые","Прямоугольные"],name:"Nimani",subName:'Пластиковые,Прямоугольные'},
    {id: 40, title: 'Очки номер 2', url:"/images/newPhotos2/40.jpg",category:["all","Пластиковые","Прямоугольные"],name:"Flavio",subName:'Пластиковые,Прямоугольные'},
    {id: 41, title: 'Очки номер 2', url:"/images/newPhotos2/41.jpg",category:["all","Пластиковые","Прямоугольные"],name:"Nimani",subName:'Пластиковые,Прямоугольные'},
    {id: 42, title: 'Очки номер 2', url:"/images/newPhotos2/42.jpg",category:["all","Овальные","Пластиковые"],name:"CityPrince",subName:'Пластиковые,Овальные'},
    {id: 43, title: 'Очки номер 2', url:"/images/newPhotos2/43.jpg",category:["all","Пластиковые","Прямоугольные"],name:"CityPrince",subName:'Пластиковые,Прямоугольные'},
    {id: 44, title: 'Очки номер 2', url:"/images/newPhotos2/44.jpg",category:["all","Пластиковые","Прямоугольные"],name:"CityPrince",subName:'Пластиковые,Прямоугольные'},
    {id: 45, title: 'Очки номер 2', url:"/images/newPhotos2/45.jpg",category:["all","Овальные","Пластиковые"],name:"BabyLook",subName:'Пластиковые,Овальные'},
    {id: 46, title: 'Очки номер 2', url:"/images/newPhotos2/46.jpg",category:["all","Кошачий глаз","Пластиковые"],name:"BabyLook",subName:'Пластиковые,"Кошачий глаз"'},
    {id: 47, title: 'Очки номер 2', url:"/images/newPhotos2/47.jpg",category:["all","Металлические","Овальные"],name:"Название",subName:'Металлические,Овальные'},
    {id: 48, title: 'Очки номер 2', url:"/images/newPhotos2/48.jpg",category:["all","Металлические","Прямоугольные"],name:"Название",subName:'Металлические,Прямоугольные'},
    {id: 49, title: 'Очки номер 2', url:"/images/newPhotos2/49.jpg",category:["all","Пластиковые","Прямоугольные"],name:"BabyLook",subName:'Пластиковые,Прямоугольные'},
    {id: 50, title: 'Очки номер 2', url:"/images/newPhotos2/50.jpg",category:["all","Пластиковые","Прямоугольные"],name:"BabyLook",subName:'Пластиковые,Прямоугольные'},
    {id: 51, title: 'Очки номер 2', url:"/images/newPhotos2/51.jpg",category:["all","Пластиковые","Прямоугольные"],name:"Dario",subName:'Пластиковые,Прямоугольные'},
    {id: 52, title: 'Очки номер 2', url:"/images/newPhotos2/52.jpg",category:["all","Пластиковые","Прямоугольные"],name:"Genex",subName:'Пластиковые,Прямоугольные'},
    {id: 53, title: 'Очки номер 2', url:"/images/newPhotos2/53.jpg",category:["all","Пластиковые","Прямоугольные"],name:"JuniorLook",subName:'Пластиковые,Прямоугольные'},
    {id: 54, title: 'Очки номер 2', url:"/images/newPhotos2/54.jpg",category:["all","Пластиковые","Прямоугольные"],name:"JuniorLook",subName:'Пластиковые,Прямоугольные'},
    {id: 55, title: 'Очки номер 2', url:"/images/newPhotos2/55.jpg",category:["all","Круглые","Металлические"],name:"JuniorLook",subName:'Пластиковые,Круглые'},
    {id: 56, title: 'Очки номер 2', url:"/images/newPhotos2/56.jpg",category:["all","Пластиковые","Прямоугольные"],name:"JuniorLook",subName:'Пластиковые,Прямоугольные'},
    {id: 57, title: 'Очки номер 2', url:"/images/newPhotos2/57.jpg",category:["all","Пластиковые","Прямоугольные"],name:"JuniorLook",subName:'Пластиковые,Прямоугольные'},
    {id: 58, title: 'Очки номер 2', url:"/images/newPhotos2/58.jpg",category:["all","Пластиковые","Прямоугольные"],name:"JuniorLook",subName:'Пластиковые,Прямоугольные'},
    {id: 59, title: 'Очки номер 2', url:"/images/newPhotos2/59.jpg",category:["all","Пластиковые","Прямоугольные"],name:"Ligas",subName:'Пластиковые,Прямоугольные'},
    {id: 60, title: 'Очки номер 2', url:"/images/newPhotos2/60.jpg",category:["all","Пластиковые","Прямоугольные"],name:"Ballet",subName:'Пластиковые,Прямоугольные'},
    {id: 61, title: 'Очки номер 2', url:"/images/newPhotos2/61.jpg",category:["all","Круглые","Металлические"],name:"Ballet",subName:'Металлические,Круглые'},
    {id: 62, title: 'Очки номер 2', url:"/images/newPhotos2/62.jpg",category:["all","Круглые","Металлические"],name:"Antonio Sordi",subName:'Металлические,Круглые'},
    {id: 63, title: 'Очки номер 2', url:"/images/newPhotos2/63.jpg",category:["all","Металлические","Прямоугольные"],name:"DIPLOMAT",subName:'Металлические,Прямоугольные'},
    {id: 64, title: 'Очки номер 2', url:"/images/newPhotos2/64.jpg",category:["all","Металлические","Прямоугольные"],name:"Ligas",subName:'Металлические,Прямоугольные'},
    {id: 65, title: 'Очки номер 2', url:"/images/newPhotos2/65.jpg",category:["all","Металлические","Прямоугольные"],name:"RIVA",subName:'Металлические,Прямоугольные'},
    {id: 66, title: 'Очки номер 2', url:"/images/newPhotos2/66.jpg",category:["all","Кошачий глаз","Металлические"],name:"Genex",subName:'Металлические,"Кошачий глаз"'},
    {id: 67, title: 'Очки номер 2', url:"/images/newPhotos2/67.jpg",category:["all","Кошачий глаз","Металлические"],name:"JuniorLook",subName:'Металлические,"Кошачий глаз"'},
    {id: 68, title: 'Очки номер 2', url:"/images/newPhotos2/68.jpg",category:["all","Металлические","Прямоугольные"],name:"Oliver WOOD",subName:'Металлические,Прямоугольные'},
    {id: 69, title: 'Очки номер 2', url:"/images/newPhotos2/69.jpg",category:["all","Круглые","Металлические"],name:"Consul",subName:'Металлические,Круглые'},
    {id: 70, title: 'Очки номер 2', url:"/images/newPhotos2/70.jpg",category:["all","Круглые","Металлические"],name:"Oliver WOOD",subName:'Металлические,Круглые'},
    {id: 71, title: 'Очки номер 2', url:"/images/newPhotos2/71.jpg",category:["all","Круглые","Металлические"],name:"GRAND",subName:'Металлические,Круглые'},
    {id: 72, title: 'Очки номер 2', url:"/images/newPhotos2/72.jpg",category:["all","Круглые","Металлические"],name:"Название",subName:'Металлические,Круглые'},
    {id: 73, title: 'Очки номер 2', url:"/images/newPhotos2/73.jpg",category:["all","Овальные","Пластиковые"],name:"BabyLook",subName:'Пластиковые,Овальные'}
]