export const productsPageProducts = [
    {id: 1, url:"/images/newPhotos2/1.jpg",category:["all","Унисекс","Квадратные","Пластиковые"],name:"Nimani",subName:'Пластиковые,Квадратные'},
    {id: 2, url:"/images/newPhotos2/2.jpg",category:["all","Женские","Овальные","Пластиковые"],name:"Nimani",subName:'Пластиковые,Овальные'},
    {id: 3, url:"/images/newPhotos2/3.jpg",category:["all","Женские","Овальные","Пластиковые"],name:"Nimani",subName:'Пластиковые,Овальные'},
    {id: 4, url:"/images/newPhotos2/4.jpg",category:["all","Унисекс","Квадратные","Пластиковые"],name:"Nimani",subName:'Пластиковые,Квадратные'},
    {id: 5, url:"/images/newPhotos2/5.jpg",category:["all","Женские","Мужские","Овальные","Пластиковые"],name:"Nimani",subName:'Пластиковые,Овальные'},
    {id: 6, url:"/images/newPhotos2/6.jpg",category:["all","Женские","Детские","Пластиковые","Прямоугольные"],name:"Nimani",subName:'Пластиковые,Прямоугольные'},
    {id: 7, url:"/images/newPhotos2/7.jpg",category:["all","Унисекс","Квадратные","Пластиковые"],name:"Nimani",subName:'Пластиковые,Квадратные'},
    {id: 8, url:"/images/newPhotos2/8.jpg",category:["all","Женские","Мужские","Квадратные","Пластиковые"],name:"Nimani",subName:'Пластиковые,Квадратные'},
    {id: 9, url:"/images/newPhotos2/9.jpg",category:["all","Женские","Пластиковые","Прямоугольные"],name:"Nimani",subName:'Пластиковые,Прямоугольные'},
    {id: 10, url:"/images/newPhotos2/10.jpg",category:["all","Унисекс","Квадратные","Пластиковые"],name:"Nimani",subName:'Пластиковые,Квадратные'},
    {id: 11, url:"/images/newPhotos2/11.jpg",category:["all","Женские","Кошачий глаз","Пластиковые"],name:"POLIVIZOR",subName:'Пластиковые,"Кошачий глаз"'},
    {id: 12, url:"/images/newPhotos2/12.jpg",category:["all","Женские","Кошачий глаз","Пластиковые"],name:"NEOLOOK",subName:'Пластиковые,"Кошачий глаз"'},
    {id: 13, url:"/images/newPhotos2/13.jpg",category:["all","Женские","Кошачий глаз","Пластиковые"],name:"NEOLOOK",subName:'Пластиковые,"Кошачий глаз"'},
    {id: 14, url:"/images/newPhotos2/14.jpg",category:["all","Женские","Кошачий глаз","Пластиковые"],name:"RIVA",subName:'Пластиковые,"Кошачий глаз"'},
    {id: 15, url:"/images/newPhotos2/15.jpg",category:["all","Женские","Кошачий глаз","Пластиковые"],name:"RIVA",subName:'Пластиковые,"Кошачий глаз"'},
    {id: 16, url:"/images/newPhotos2/16.jpg",category:["all","Женские","Кошачий глаз","Пластиковые"],name:"RIVA",subName:'Пластиковые,"Кошачий глаз"'},
    {id: 17, url:"/images/newPhotos2/17.jpg",category:["all","Женские","Кошачий глаз","Пластиковые"],name:"RIVA",subName:'Пластиковые,"Кошачий глаз"'},
    {id: 18, url:"/images/newPhotos2/18.jpg",category:["all","Женские","Кошачий глаз","Металлические"],name:"Antonio Sordi",subName:'Металлические,"Кошачий глаз"'},
    {id: 19, url:"/images/newPhotos2/19.jpg",category:["all","Женские","Кошачий глаз","Пластиковые"],name:"POLIVIZOR",subName:'Пластиковые,"Кошачий глаз"'},
    {id: 20, url:"/images/newPhotos2/20.jpg",category:["all","Женские","Кошачий глаз","Пластиковые"],name:"Ligas",subName:'Пластиковые,"Кошачий глаз"'},
    {id: 21, url:"/images/newPhotos2/21.jpg",category:["all","Женские","Кошачий глаз","Пластиковые"],name:"POLIVIZOR",subName:'Пластиковые,"Кошачий глаз"'},
    {id: 22, url:"/images/newPhotos2/22.jpg",category:["all","Женские","Кошачий глаз","Металлические"],name:"Ligas",subName:'Металлические,"Кошачий глаз"'},
    {id: 23, url:"/images/newPhotos2/23.jpg",category:["all","Женские","Кошачий глаз","Металлические"],name:"NEOLOOK",subName:'Металлические,"Кошачий глаз"'},
    {id: 24, url:"/images/newPhotos2/24.jpg",category:["all","Женские","Пластиковые","Прямоугольные"],name:"Antonio Sordi",subName:'Пластиковые,Прямоугольные'},
    {id: 25, url:"/images/newPhotos2/25.jpg",category:["all","Женские","Кошачий глаз","Металлические"],name:"RIVA",subName:'Металлические,"Кошачий глаз"'},
    {id: 26, url:"/images/newPhotos2/26.jpg",category:["all","Женские","Кошачий глаз","Металлические"],name:"NEOLOOK",subName:'Металлические,"Кошачий глаз"'},
    {id: 27, url:"/images/newPhotos2/27.jpg",category:["all","Женские","Кошачий глаз","Металлические"],name:"Genex",subName:'Металлические,"Кошачий глаз"'},
    {id: 28, url:"/images/newPhotos2/28.jpg",category:["all","Женские","Кошачий глаз","Металлические"],name:"RIVA",subName:'Металлические,"Кошачий глаз"'},
    {id: 29, url:"/images/newPhotos2/29.jpg",category:["all","Женские","Кошачий глаз","Металлические"],name:"RIVA",subName:'Металлические,"Кошачий глаз"'},
    {id: 30, url:"/images/newPhotos2/30.jpg",category:["all","Мужские","Металлические","Прямоугольные"],name:"Flavio",subName:'Металлические,Прямоугольные'},
    {id: 31, url:"/images/newPhotos2/31.jpg",category:["all","Женские","Металлические","Прямоугольные"],name:"Ricardo Rossi",subName:'Металлические,Прямоугольные'},
    {id: 32, url:"/images/newPhotos2/32.jpg",category:["all","Женские","Металлические","Прямоугольные"],name:"Ricardo Rossi",subName:'Металлические,Прямоугольные'},
    {id: 33, url:"/images/newPhotos2/33.jpg",category:["all","Мужские","Металлические","Прямоугольные"],name:"Ballet",subName:'Металлические,Прямоугольные'},
    {id: 34, url:"/images/newPhotos2/34.jpg",category:["all","Мужские","Металлические","Прямоугольные"],name:"Elfspirit",subName:'Металлические,Прямоугольные'},
    {id: 35, url:"/images/newPhotos2/35.jpg",category:["all","Унисекс","Металлические","Прямоугольные"],name:"Ballet",subName:'Металлические,Прямоугольные'},
    {id: 36, url:"/images/newPhotos2/36.jpg",category:["all","Мужские","Металлические","Прямоугольные"],name:"Elfspirit",subName:'Металлические,Прямоугольные'},
    {id: 37, url:"/images/newPhotos2/37.jpg",category:["all","Унисекс","Пластиковые","Прямоугольные"],name:"Ballet",subName:'Пластиковые,Прямоугольные'},
    {id: 38, url:"/images/newPhotos2/38.jpg",category:["all","Унисекс","Пластиковые","Прямоугольные"],name:"ZENO",subName:'Пластиковые,Прямоугольные'},
    {id: 39, url:"/images/newPhotos2/39.jpg",category:["all","Унисекс","Пластиковые","Прямоугольные"],name:"Nimani",subName:'Пластиковые,Прямоугольные'},
    {id: 40, url:"/images/newPhotos2/40.jpg",category:["all","Мужские","Пластиковые","Прямоугольные"],name:"Flavio",subName:'Пластиковые,Прямоугольные'},
    {id: 41, url:"/images/newPhotos2/41.jpg",category:["all","Унисекс","Пластиковые","Прямоугольные"],name:"Nimani",subName:'Пластиковые,Прямоугольные'},
    {id: 42, url:"/images/newPhotos2/42.jpg",category:["all","Детские","Овальные","Пластиковые"],name:"CityPrince",subName:'Пластиковые,Овальные'},
    {id: 43, url:"/images/newPhotos2/43.jpg",category:["all","Детские","Пластиковые","Прямоугольные"],name:"CityPrince",subName:'Пластиковые,Прямоугольные'},
    {id: 44, url:"/images/newPhotos2/44.jpg",category:["all","Детские","Пластиковые","Прямоугольные"],name:"CityPrince",subName:'Пластиковые,Прямоугольные'},
    {id: 45, url:"/images/newPhotos2/45.jpg",category:["all","Детские","Овальные","Пластиковые"],name:"BabyLook",subName:'Пластиковые,Овальные'},
    {id: 46, url:"/images/newPhotos2/46.jpg",category:["all","Детские","Кошачий глаз","Пластиковые"],name:"BabyLook",subName:'Пластиковые,"Кошачий глаз"'},
    {id: 47, url:"/images/newPhotos2/47.jpg",category:["all","Детские","Металлические","Овальные"],name:"BabyVision",subName:'Металлические,Овальные'},
    {id: 48, url:"/images/newPhotos2/48.jpg",category:["all","Детские","Металлические","Прямоугольные"],name:"BabyVision",subName:'Металлические,Прямоугольные'},
    {id: 49, url:"/images/newPhotos2/49.jpg",category:["all","Детские","Пластиковые","Прямоугольные"],name:"BabyLook",subName:'Пластиковые,Прямоугольные'},
    {id: 50, url:"/images/newPhotos2/50.jpg",category:["all","Детские","Пластиковые","Прямоугольные"],name:"BabyLook",subName:'Пластиковые,Прямоугольные'},
    {id: 51, url:"/images/newPhotos2/51.jpg",category:["all","Подростковые","Пластиковые","Прямоугольные"],name:"Dario",subName:'Пластиковые,Прямоугольные'},
    {id: 52, url:"/images/newPhotos2/52.jpg",category:["all","Подростковые","Пластиковые","Прямоугольные"],name:"Genex",subName:'Пластиковые,Прямоугольные'},
    {id: 53, url:"/images/newPhotos2/53.jpg",category:["all","Подростковые","Пластиковые","Прямоугольные"],name:"JuniorLook",subName:'Пластиковые,Прямоугольные'},
    {id: 54, url:"/images/newPhotos2/54.jpg",category:["all","Подростковые","Пластиковые","Прямоугольные"],name:"JuniorLook",subName:'Пластиковые,Прямоугольные'},
    {id: 55, url:"/images/newPhotos2/55.jpg",category:["all","Подростковые","Круглые","Металлические"],name:"JuniorLook",subName:'Металлические,Круглые'},
    {id: 56, url:"/images/newPhotos2/56.jpg",category:["all","Подростковые","Пластиковые","Прямоугольные"],name:"JuniorLook",subName:'Пластиковые,Прямоугольные'},
    {id: 57, url:"/images/newPhotos2/57.jpg",category:["all","Подростковые","Пластиковые","Прямоугольные"],name:"JuniorLook",subName:'Пластиковые,Прямоугольные'},
    {id: 58, url:"/images/newPhotos2/58.jpg",category:["all","Подростковые","Пластиковые","Прямоугольные"],name:"JuniorLook",subName:'Пластиковые,Прямоугольные'},
    {id: 59, url:"/images/newPhotos2/59.jpg",category:["all","Подростковые","Пластиковые","Прямоугольные"],name:"Ligas",subName:'Пластиковые,Прямоугольные'},
    {id: 60, url:"/images/newPhotos2/60.jpg",category:["all","Подростковые","Пластиковые","Прямоугольные"],name:"Ballet",subName:'Пластиковые,Прямоугольные'},
    {id: 61, url:"/images/newPhotos2/61.jpg",category:["all","Унисекс","Круглые","Металлические"],name:"Ballet",subName:'Металлические,Круглые'},
    {id: 62, url:"/images/newPhotos2/62.jpg",category:["all","Унисекс","Круглые","Металлические"],name:"Antonio Sordi",subName:'Металлические,Круглые'},
    {id: 63, url:"/images/newPhotos2/63.jpg",category:["all","Унисекс","Металлические","Прямоугольные"],name:"DIPLOMAT",subName:'Металлические,Прямоугольные'},
    {id: 64, url:"/images/newPhotos2/64.jpg",category:["all","Женские","Металлические","Прямоугольные"],name:"Ligas",subName:'Металлические,Прямоугольные'},
    {id: 65, url:"/images/newPhotos2/65.jpg",category:["all","Женские","Металлические","Прямоугольные"],name:"RIVA",subName:'Металлические,Прямоугольные'},
    {id: 66, url:"/images/newPhotos2/66.jpg",category:["all","Женские","Кошачий глаз","Металлические"],name:"Genex",subName:'Металлические,"Кошачий глаз"'},
    {id: 67, url:"/images/newPhotos2/67.jpg",category:["all","Подростковые","Кошачий глаз","Металлические"],name:"JuniorLook",subName:'Металлические,"Кошачий глаз"'},
    {id: 68, url:"/images/newPhotos2/68.jpg",category:["all","Унисекс","Металлические","Прямоугольные"],name:"Oliver WOOD",subName:'Металлические,Прямоугольные'},
    {id: 69, url:"/images/newPhotos2/69.jpg",category:["all","Унисекс","Круглые","Металлические"],name:"Consul",subName:'Металлические,Круглые'},
    {id: 70, url:"/images/newPhotos2/70.jpg",category:["all","Унисекс","Круглые","Металлические"],name:"Oliver WOOD",subName:'Металлические,Круглые'},
    {id: 71, url:"/images/newPhotos2/71.jpg",category:["all","Унисекс","Круглые","Металлические"],name:"GRAND",subName:'Металлические,Круглые'},
    {id: 72, url:"/images/newPhotos2/72.jpg",category:["all","Унисекс","Круглые","Металлические"],name:"BabyVision",subName:'Металлические,Круглые'},
    {id: 73, url:"/images/newPhotos2/73.jpg",category:["all","Детские","Овальные","Пластиковые"],name:"BabyLook",subName:'Пластиковые,Овальные'},
    {id: 74,lensText:"Классические линзы", url:"/images/newPhotos2/73.jpg",category:["all","Линзы"],name:"Линзы без покрытий",subName:''},
    {id: 75,lensText:"Стекла внешне выглядят совершенно прозрачно, и окружающие видят ваши красивые глаза, а не мелькающие отсветы", url:"/images/newPhotos2/73.jpg",category:["all","Линзы"],name:"Линзы с антибликовым покрытием",subName:''},
    {id: 76,lensText:"Линзы для очков с утонченным дизайном являются более легкими и изящными", url:"/images/newPhotos2/73.jpg",category:["all","Линзы"],name:"Утончённые линзы",subName:''},
    {id: 77,lensText:"Помогают решить как дальнозоркость, так и близорукость, а также проблемы со средней дистанцией, без отвлекающего перехода", url:"/images/newPhotos2/73.jpg",category:["all","Линзы"],name:"Прогрессивные линзы",subName:''},
    {id: 78,lensText:"Верхняя половина линзы корректирует близорукость, а нижняя половина корректирует дальнозоркость", url:"/images/newPhotos2/73.jpg",category:["all","Линзы"],name:"Бифокальные линзы",subName:''},
    {id: 79, lensText:"Цвет и светопропускание линз меняется от воздействия ультрафиолетовых лучей. То есть чем ярче светит солнце, тем темнее становятся линзы очков.", url:"/images/newPhotos2/73.jpg",category:["all","Линзы"],name:"Фотохромные линзы",subName:''},
    {id: 80, lensText:"Такие линзы позволяют водителям лучше различать обстановку на дороге благодаря увеличению светопропускания и уменьшению мешающих отражений",url:"/images/newPhotos2/73.jpg",category:["all","Линзы"],name:"Линзы для вождения в вечернее и ночное время суток",subName:''},

]